### PR TITLE
Small OpenEXR loader fix

### PR DESCRIPTION
**Pull request by AnastaZIuk**

### CODE REVIEW

**Comment by devshgraphicsprogramming** [comment]
writer?

**Comment by AnastaZIuk** [comment]
I'm dealing with it right now :D

**Comment by devshgraphicsprogramming** [comment]
why did you add denoised images to our repo?

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk would you mind converting the .hdri envmaps to OpenEXR?

**Comment by AnastaZIuk** [comment]
> @AnastaZIuk would you mind converting the .hdri envmaps to OpenEXR?

okay, I will do it

**Pull request merged**
