### PR TITLE
Builtin resources - Builtindatagen.py error logging

### PR DESCRIPTION
**Pull request by Hazardu**
I found it slightly bothersome that the errors during generating builtin resources weren't showing

### CODE REVIEW

**Comment by devshgraphicsprogramming** [comment]
could you also tackle this week's bug with the missing builtin data in this PR?

**Comment by Hazardu** [comment]
sure

**Comment by Hazardu** [comment]
ive merged the latest changes to this branch, yet it does not appear to skip any files in the generated .cpp file

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk provide counter example

**Pull request merged**
